[build]
builder = "DOCKER"

[build.env]
NIXPACKS_NODE_VERSION = "22.14.0"
NODE_VERSION = "22.14.0"

[phases.install]
cmds = [
    "rm -rf package-lock.json website/package-lock.json server/package-lock.json",
    "rm -rf node_modules website/node_modules server/node_modules",
    "npm install"
]
