services:
  - type: web
    name: ludo-star-server
    env: node
    plan: free
    buildCommand: "cd website && npm install && npm run build && cd ../server && npm install"
    startCommand: "cd server && node server.js"
    envVars:
      - key: NODE_ENV
        value: production
